select distinct `stand`.`team`                                               AS `team`,
                `conference`                                         AS `conference`,
                `season`                                             AS `season`,
                `W`                                                  AS `wins`,
                `L`                                                  AS `loses`,
                `PCT`                                                AS `pct`,
                `GB`                                                 AS `gb`,
                substr(`HOME`, 1, (locate('-', `HOME`) - 1)) AS `home_wins`,
                substr(`HOME`, (locate('-', `HOME`) + 1))    AS `home_loses`,
                substr(`AWAY`, 1, (locate('-', `AWAY`) - 1)) AS `away_wins`,
                substr(`AWAY`, (locate('-', `AWAY`) + 1))    AS `away_loses`,
                substr(`DIV`, 1, (locate('-', `DIV`) - 1))   AS `div_wins`,
                substr(`DIV`, (locate('-', `DIV`) + 1))      AS `div_loses`,
                substr(`CONF`, 1, (locate('-', `CONF`) - 1)) AS `conf_wins`,
                substr(`CONF`, (locate('-', `CONF`) + 1))    AS `conf_loses`,
                `PPG`                                                AS `ppg`,
                `OPP_PPG`                                            AS `opp_ppg`,
                `DIFF`                                               AS `diff`,
                `STRK`                                               AS `strk`,
                `L10`                                                AS `last_10`,
                source_link,
                stand.created_at
from (`team_standings` `stand`
       join `team_info` `team` on ((`stand`.`team` = `team`.`TEAM`)))
